# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: "3.7"

services:
  authentication-service:
    image: authentication-service
    container_name: authentication-service
    build:
      context: .
      args:
        jarFile: "build/libs/authentication-service-core-1.0.jar"
    depends_on:
      - wiremock
    environment:
      SMS_GATE_URL: "http://wiremock:8080"
    ports:
      - "8080:8080"
    restart: always

  wiremock:
    image: holomekc/wiremock-gui
    container_name: wiremock
    ports:
      - "8081:8080"
    restart: always
